networks:
  video_generation:
    external: true
    name: Video Generation
services:
  tiktok-api:
    build: .
    networks:
      video_generation:
        ipv4_address: 10.20.0.17
    ports:
      - 8771:8048
    restart: unless-stopped
    volumes:
      - tiktok-uploader-3_cookies:/app/cookies
volumes:
  tiktok-uploader-3_cookies:
    name: tiktok-uploader-3_cookies